language: generic

sudo: required

services:
    - docker

script:
    - docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ -w /root/src/ $DOCKER_IMAGE /bin/bash .travis-build.sh $DOCKER_IMAGE

env:
    - DOCKER_IMAGE=centos:8
    - DOCKER_IMAGE=fedora:30
    - DOCKER_IMAGE=fedora:31
    - DOCKER_IMAGE=fedora:32
    - DOCKER_IMAGE=fedora:rawhide
