# Generated by Django 2.2.13 on 2020-11-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEdits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(max_length=6)),
                ('trange', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('ident', models.CharField(max_length=20)),
                ('network', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StationEdits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(max_length=6)),
                ('trange', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('ident', models.CharField(max_length=20)),
                ('network', models.CharField(max_length=20)),
                ('lon', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('startDate', models.DateTimeField()),
                ('finalDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
