# Generated by Django 2.2.13 on 2020-11-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0002_dataedits_stationedits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataedits',
            name='ident',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
