# Generated by Django 2.2.13 on 2020-11-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0003_auto_20201113_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationedits',
            name='ident',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
