# Generated by Django 2.2.13 on 2020-11-15 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0004_auto_20201113_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataEdits',
            new_name='DataEdit',
        ),
        migrations.RenameModel(
            old_name='StationEdits',
            new_name='StationEdit',
        ),
    ]
