# Generated by Django 2.2.13 on 2020-11-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0005_auto_20201115_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('i', 'Invalidation'), ('v', 'Validation')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='dataedit',
            name='edit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dynamic.Edit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationedit',
            name='edit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dynamic.Edit'),
            preserve_default=False,
        ),
    ]
