# Generated by Django 2.2.13 on 2020-11-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0006_auto_20201115_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='data_type',
            field=models.CharField(choices=[('s', 'Station'), ('d', 'Data')], default='d', max_length=1),
        ),
    ]
