# Generated by Django 2.2.13 on 2020-11-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0007_edit_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='finalDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edit',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
